### ISSUE TITLE
[Bug Report] - Accuracy shows NaN%

### ISSUE THREAD

**Issue by nczitzk** [gamer-ai/eletype-frontend#21]
If I clear all the words I typed before the countdown, Accuracy will be `NaN`. It seems to be a `0 / 0` problem.

It is a cool web app to spend time on btw! 😄

**Comment by MUYANGGUO** [comment]
Thanks for flagging and making it better , PR merged and welcome to channel https://discord.gg/KGYJt7nJ if interested! @nczitzk ❤️👍
